// Regenerates the typed API contract from the backend's OpenAPI file.
//
//   pnpm api:types                      # reads ../EducationERP/docs/api/openapi.yaml
//   OPENAPI=path/to/openapi.yaml pnpm api:types
//
// Writes:
//   src/shared/api/schema.gen.ts  — openapi-typescript output (paths + components)
//   src/shared/api/enums.gen.ts   — every enum's value → label map, parsed from the
//                                    "* `value` - Label" descriptions drf-spectacular emits,
//                                    so the UI shows the label and sends the value.
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { parse } from 'yaml'

const source = resolve(process.env.OPENAPI ?? '../EducationERP/docs/api/openapi.yaml')
const outDir = resolve('src/shared/api')

execFileSync('node_modules/.bin/openapi-typescript', [source, '-o', `${outDir}/schema.gen.ts`], { stdio: 'inherit' })

const doc = parse(readFileSync(source, 'utf8'))
const lines = [
  '// Generated by scripts/generate-api.mjs from openapi.yaml — do not edit by hand.',
  '/* eslint-disable */',
  '',
  'export const enumLabels = {',
]
for (const [name, schema] of Object.entries(doc.components.schemas).sort()) {
  if (!Array.isArray(schema.enum)) continue
  const labels = {}
  for (const m of (schema.description ?? '').matchAll(/^\* `([^`]*)` - (.+)$/gm)) labels[m[1]] = m[2].trim()
  const entries = schema.enum
    .filter((v) => typeof v === 'string' && v !== '')
    .map((v) => `    ${JSON.stringify(v)}: ${JSON.stringify(labels[v] ?? v)},`)
  lines.push(`  ${name}: {`, ...entries, '  },')
}
lines.push('} as const', '', 'export type EnumName = keyof typeof enumLabels', '')
writeFileSync(`${outDir}/enums.gen.ts`, lines.join('\n'))
console.log(`enums.gen.ts written from ${source}`)
